language: r
warnings_are_errors: true
sudo: required
r:
 - 3.1
 - oldrel
 - release
 - devel

r_binary_packages:
  - dplyr
  - tidyr
  - ggplot2
  - testthat
  - changepoint
  - dlm
  - forecast
  - KFAS
  - knitr
  - MASS
  - MSwM
  - ROCR
  - sp
  - strucchange
  - survival
  - timeSeries
  - vars
  - xts
  - raster
  - roxygen2
  - covr

before_install:
  - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" >> ~/.Rprofile

after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'
